# Generated by Django 6.0.1 on 2026-01-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Теги (через запятую)"
            ),
        ),
    ]
